// Shared blog post data — single source of truth.
// Imported by BlogIndex.jsx and FromTheBlog.jsx.
// When adding new posts, update this file only.

export const ALL_POSTS = [
  {
    slug: 'how-to-manage-a-rental-property',
    href: '/blog/how-to-manage-a-rental-property',
    title: 'How to manage a <em>rental property:</em> a practical guide for landlords.',
    dek: 'Managing a rental property goes well beyond collecting rent. This practical guide covers tenant screening, maintenance, Maryland landlord-tenant law, financial tracking, and how to know when professional management is a better return on your time.',
    category: { id: 'rental', label: 'Rental Management', tone: '' },
    date: 'May 16, 2026', dateIso: '2026-05-16',
    readTime: 9,
    author: 'Cody Bishop',
    tone: '',
    featured: true,
    coverImage: '/assets/how-to-manage-a-rental-property.jpg',
    coverAlt: 'Landlord conducting a rental property inspection and documenting condition with a phone camera',
  },
  {
    slug: 'what-is-a-community-association-manager',
    href: '/blog/what-is-a-community-association-manager',
    title: 'What is a <em>community association manager?</em> Roles, responsibilities, and what your board should expect.',
    dek: 'A community association manager (CAM) is the professional hired by an HOA or condo board to handle day-to-day community operations. This guide covers what a CAM does, how the role works with the board, what credentials matter, and how to tell if your management company is meeting the standard.',
    category: { id: 'hoa-mgmt', label: 'HOA Management', tone: '' },
    date: 'May 15, 2026', dateIso: '2026-05-15',
    readTime: 9,
    author: 'Marcia Goldstein',
    tone: '',
    coverImage: '/assets/what-is-a-community-association-manager.jpg',
    coverAlt: 'Community association manager shaking hands with HOA board members outside a community clubhouse',
  },
  {
    slug: 'what-is-quorum-and-why-is-it-important',
    href: '/blog/what-is-quorum-and-why-is-it-important',
    title: 'What is a quorum? <em>Definition,</em> requirements, and why it matters for your board.',
    dek: "A quorum is the minimum number of members who must be present for a meeting\'s decisions to be legally valid. This guide covers how quorum works for HOA board meetings and annual meetings, what happens when quorum isn\'t met, and how proxy voting affects the count.",
    category: { id: 'governance', label: 'Board Governance', tone: '' },
    date: 'May 14, 2026', dateIso: '2026-05-14',
    readTime: 8,
    author: 'Marcia Goldstein',
    tone: '',
    coverImage: '/assets/quorum-community-manager.jpg',
    coverAlt: 'Tidewater community association manager walking through a planned neighborhood in Maryland, holding an iPad during a site inspection',
  },
  {
    slug: 'how-to-switch-hoa-management-companies',
    href: '/blog/how-to-switch-hoa-management-companies',
    title: 'How to switch HOA management companies: a <em>step-by-step</em> guide.',
    dek: 'Switching HOA management companies follows a predictable process when you know the steps. This guide covers contract review, board votes, notice requirements, financial and records transfer, and how to evaluate your next management partner.',
    category: { id: 'hoa-mgmt', label: 'HOA Management', tone: '' },
    date: 'May 14, 2026', dateIso: '2026-05-14',
    readTime: 9,
    author: 'Rachel Halverson',
    tone: '',
    coverImage: '/assets/how-to-switch-hoa-management-companies.jpg',
    coverAlt: 'HOA board members reviewing management company transition documents',
  },
  {
    slug: 'self-managed-to-professional',
    href: '/solutions/self-managed-hoa-transition',
    title: 'From self-managed to professional: what actually changes.',
    dek: 'The board still decides; the admin moves to us. A clear-eyed framework for self-managed boards considering professional management.',
    category: { id: 'solutions', label: 'Solutions', tone: '' },
    date: 'March 18, 2026', dateIso: '2026-03-18',
    readTime: 6,
    author: 'Marcia Goldstein',
    tone: '',
    coverImage: '/assets/tidewater-self-managed-hoa-board-members-frustrated.jpg',
    coverAlt: 'Self-managed HOA board members reviewing financial documents at a community meeting',
  },
];
